#!/bin/bash

# === kdescribe ===
# Describe a Kubernetes pod or deployment by partial match
# Usage: kdescribe <search-term> [-n namespace] [-t type]
# Defaults: namespace="default", type="pod"

SEARCH=""
NAMESPACE="default"
TYPE="pod"

# Parse args
while [[ $# -gt 0 ]]; do
  case $1 in
    -n|--namespace)
      NAMESPACE="$2"
      shift 2
      ;;
    -t|--type)
      TYPE="$2"
      shift 2
      ;;
    *)
      SEARCH="$1"
      shift
      ;;
  esac
done

if [[ -z "$SEARCH" ]]; then
  echo "Usage: kdescribe <search-term> [-n namespace] [-t type]"
  exit 1
fi

echo "Searching for $TYPE(s) matching \"$SEARCH\" in namespace \"$NAMESPACE\"..."

MATCHES=($(kubectl get $TYPE -n "$NAMESPACE" --no-headers | awk '{print $1}' | grep "$SEARCH"))

if [[ ${#MATCHES[@]} -eq 0 ]]; then
  echo "No $TYPE found matching \"$SEARCH\"."
  exit 1
elif [[ ${#MATCHES[@]} -eq 1 ]]; then
  SELECTED="${MATCHES[0]}"
else
  echo "Multiple matches found:"
  for i in "${!MATCHES[@]}"; do
    echo " $((i+1))) ${MATCHES[$i]}"
  done
  read -rp "Select a number: " SELECTED_INDEX
  SELECTED="${MATCHES[$((SELECTED_INDEX-1))]}"
fi

echo "Describing $TYPE: $SELECTED"
kubectl describe $TYPE "$SELECTED" -n "$NAMESPACE"